# -*- coding: utf-8 -*-
"""dashboard_mineria_datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnbAwW2lFQD_tVEEsu1e9utmcJlAPqIG
"""



import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from xgboost import XGBClassifier
import numpy as np






app = dash.Dash(__name__)
server = app.server




df = pd.read_csv("df_final_flores.csv")




# ======================================================
# CARGAR DATASET
# ======================================================

df = pd.read_csv("df_final_flores.csv")

# ======================================================
# LIMPIEZA
# ======================================================

df = df.dropna()

df["Fecha"] = pd.to_datetime(df["Fecha"])

df["Año"] = df["Fecha"].dt.year
df["Mes"] = df["Fecha"].dt.month_name()

# ======================================================
# INICIAR APP
# ======================================================

app = dash.Dash(__name__)
server = app.server

# ======================================================
# ESTILO TARJETAS KPI
# ======================================================

CARD_STYLE = {
    "padding": "20px",
    "borderRadius": "15px",
    "color": "white",
    "width": "23%",
    "textAlign": "center",
    "boxShadow": "2px 2px 10px rgba(0,0,0,0.2)"
}

# ======================================================
# LAYOUT
# ======================================================

app.layout = html.Div([

    # ==================================================
    # TITULO
    # ==================================================

    html.H1(
        "🌸 Dashboard Ejecutivo - Florerías",
        style={
            "textAlign": "center",
            "color": "white",
            "marginBottom": "10px"
        }
    ),

    html.P(
        """
        Análisis interactivo de ventas, ingresos y rentabilidad
        de las diferentes categorías de flores.
        """,
        style={
            "textAlign": "center",
            "color": "white",
            "fontSize": "18px",
            "marginBottom": "30px"
        }
    ),

    # ==================================================
    # FILTROS
    # ==================================================

    html.Div([

        # TIENDAS
        html.Div([

            html.Label(
                "Seleccionar Tienda",
                style={"color": "white"}
            ),

            dcc.Dropdown(
                id="filtro_tienda",

                options=[
                    {"label": i, "value": i}
                    for i in df["Tienda"].unique()
                ],

                value=df["Tienda"].unique().tolist(),

                multi=True
            )

        ], style={"width": "32%"}),

        # CATEGORIAS
        html.Div([

            html.Label(
                "Seleccionar Categoría",
                style={"color": "white"}
            ),

            dcc.Dropdown(
                id="filtro_categoria",

                options=[
                    {"label": i, "value": i}
                    for i in df["Categoría"].unique()
                ],

                value=df["Categoría"].unique().tolist(),

                multi=True
            )

        ], style={"width": "32%"}),

        # AÑOS
        html.Div([

            html.Label(
                "Seleccionar Año",
                style={"color": "white"}
            ),

            dcc.Dropdown(
                id="filtro_anio",

                options=[
                    {"label": i, "value": i}
                    for i in sorted(df["Año"].unique())
                ],

                value=sorted(df["Año"].unique()),

                multi=True
            )

        ], style={"width": "32%"})

    ],
    style={
        "display": "flex",
        "justifyContent": "space-between",
        "marginBottom": "30px"
    }),

    # ==================================================
    # KPIs
    # ==================================================

    html.Div(
        id="kpis",

        style={
            "display": "flex",
            "justifyContent": "space-between",
            "marginBottom": "40px"
        }
    ),

    # ==================================================
    # GRAFICO 1
    # ==================================================

    dcc.Graph(id="linea_ventas"),

    # ==================================================
    # GRAFICOS 2 Y 3
    # ==================================================

    html.Div([

        html.Div([
            dcc.Graph(id="bar_categoria")
        ], style={"width": "49%"}),

        html.Div([
            dcc.Graph(id="bar_tienda")
        ], style={"width": "49%"})

    ],
    style={
        "display": "flex",
        "justifyContent": "space-between"
    }),

    # ==================================================
    # GRAFICOS 4 Y 5
    # ==================================================

    html.Div([

        html.Div([
            dcc.Graph(id="boxplot")
        ], style={"width": "49%"}),

        html.Div([
            dcc.Graph(id="scatter")
        ], style={"width": "49%"})

    ],
    style={
        "display": "flex",
        "justifyContent": "space-between"
    }),

    # ==================================================
    # GRAFICOS 6 Y 7
    # ==================================================

    html.Div([

        html.Div([
            dcc.Graph(id="pie")
        ], style={"width": "49%"}),

        html.Div([
            dcc.Graph(id="heatmap")
        ], style={"width": "49%"})

    ],
    style={
        "display": "flex",
        "justifyContent": "space-between"
    }),

    # ==================================================
    # SECCION MACHINE LEARNING
    # ==================================================

    html.H2(
        "🤖 Modelos de Machine Learning",
        style={
            "color": "white",
            "marginTop": "40px",
            "textAlign": "center"
        }
    ),

    html.Div([

        html.Div([
            dcc.Graph(id="clusters")
        ], style={"width": "49%"}),

        html.Div([
            dcc.Graph(id="comparacion_modelos")
        ], style={"width": "49%"})

    ],
    style={
        "display": "flex",
        "justifyContent": "space-between"
    }),

    html.Div([

        html.Div([
            dcc.Graph(id="rf_confusion")
        ], style={"width": "49%"}),

        html.Div([
            dcc.Graph(id="xgb_confusion")
        ], style={"width": "49%"})

    ],
    style={
        "display": "flex",
        "justifyContent": "space-between"
    }),

    dcc.Graph(id="importancias")

],
style={
    "backgroundColor": "#111111",
    "padding": "30px",
    "fontFamily": "Arial"
})

# ======================================================
# CALLBACK
# ======================================================

@app.callback(

    [
        Output("kpis", "children"),
        Output("linea_ventas", "figure"),
        Output("bar_categoria", "figure"),
        Output("bar_tienda", "figure"),
        Output("boxplot", "figure"),
        Output("scatter", "figure"),
        Output("pie", "figure"),
        Output("heatmap", "figure"),
        Output("clusters", "figure"),
        Output("comparacion_modelos", "figure"),
        Output("rf_confusion", "figure"),
        Output("xgb_confusion", "figure"),
        Output("importancias", "figure")
    ],

    [
        Input("filtro_tienda", "value"),
        Input("filtro_categoria", "value"),
        Input("filtro_anio", "value")
    ]

)

def actualizar_dashboard(tiendas, categorias, anios):

    # ==================================================
    # FILTRAR DATOS
    # ==================================================

    dff = df[
        (df["Tienda"].isin(tiendas)) &
        (df["Categoría"].isin(categorias)) &
        (df["Año"].isin(anios))
    ]

    # ==================================================
    # KPIs
    # ==================================================

    ingresos = dff["Ingreso_Total"].sum()
    ganancias = dff["Ganancia_Neta"].sum()
    unidades = dff["Cantidad"].sum()
    ticket = dff["Ingreso_Total"].mean()

    kpis = [

        html.Div([

            html.H3("💰 Ingresos"),
            html.H1(f"${ingresos:,.0f}")

        ],
        style={**CARD_STYLE, "backgroundColor": "#16A085"}),

        html.Div([

            html.H3("📈 Ganancia"),
            html.H1(f"${ganancias:,.0f}")

        ],
        style={**CARD_STYLE, "backgroundColor": "#2980B9"}),

        html.Div([

            html.H3("🛒 Unidades"),
            html.H1(f"{unidades:,.0f}")

        ],
        style={**CARD_STYLE, "backgroundColor": "#8E44AD"}),

        html.Div([

            html.H3("🧾 Ticket Promedio"),
            html.H1(f"${ticket:,.0f}")

        ],
        style={**CARD_STYLE, "backgroundColor": "#D35400"})

    ]

    # ==================================================
    # LINEA TEMPORAL
    # ==================================================

    ventas_fecha = dff.groupby(
        "Fecha"
    )["Ingreso_Total"].sum().reset_index()

    fig_linea = px.line(
        ventas_fecha,
        x="Fecha",
        y="Ingreso_Total",
        title="📈 Evolución Temporal de Ventas"
    )

    fig_linea.update_layout(template="plotly_dark")

    # ==================================================
    # BARRAS CATEGORIA
    # ==================================================

    categoria = dff.groupby(
        "Categoría"
    )["Ganancia_Neta"].sum().reset_index()

    fig_categoria = px.bar(
        categoria,
        x="Categoría",
        y="Ganancia_Neta",
        color="Categoría",
        title="🌸 Ganancia por Categoría"
    )

    fig_categoria.update_layout(template="plotly_dark")

    # ==================================================
    # BARRAS TIENDA
    # ==================================================

    tiendas_df = dff.groupby(
        "Tienda"
    )["Ingreso_Total"].sum().reset_index()

    fig_tienda = px.bar(
        tiendas_df,
        x="Tienda",
        y="Ingreso_Total",
        color="Tienda",
        title="🏪 Ingresos por Tienda"
    )

    fig_tienda.update_layout(template="plotly_dark")

    # ==================================================
    # BOXPLOT
    # ==================================================

    fig_box = px.box(
        dff,
        x="Categoría",
        y="Ingreso_Total",
        color="Categoría",
        title="📦 Distribución de Ingresos"
    )

    fig_box.update_layout(template="plotly_dark")

    # ==================================================
    # SCATTER
    # ==================================================

    fig_scatter = px.scatter(
        dff,
        x="Costo_Unitario",
        y="Precio_Venta_Unitario",
        size="Ganancia_Neta",
        color="Categoría",
        hover_data=["Tienda"],
        title="💲 Relación Costos vs Precio"
    )

    fig_scatter.update_layout(template="plotly_dark")

    # ==================================================
    # PIE CHART
    # ==================================================

    pie_df = dff.groupby(
        "Categoría"
    )["Ingreso_Total"].sum().reset_index()

    fig_pie = px.pie(
        pie_df,
        names="Categoría",
        values="Ingreso_Total",
        title="🥧 Participación de Ventas"
    )

    fig_pie.update_layout(template="plotly_dark")

    # ==================================================
    # HEATMAP
    # ==================================================

    columnas = [
        "Cantidad",
        "Costo_Unitario",
        "Costo_Total",
        "Precio_Venta_Unitario",
        "Ingreso_Total",
        "Ganancia_Neta"
    ]

    corr = dff[columnas].corr()

    fig_heatmap = go.Figure(

        data=go.Heatmap(
            z=corr.values,
            x=corr.columns,
            y=corr.columns,
            colorscale="RdBu",
            zmin=-1,
            zmax=1
        )

    )

    fig_heatmap.update_layout(
        title="🔥 Matriz de Correlación",
        template="plotly_dark"
    )

    # ==================================================
    # MACHINE LEARNING - FEATURES BASE
    # ==================================================

    features_ml = [
        "Cantidad",
        "Costo_Unitario",
        "Costo_Total",
        "Precio_Venta_Unitario",
        "Ingreso_Total",
        "Ganancia_Neta"
    ]

    dff_ml = dff[features_ml].dropna()

    # ==================================================
    # CLUSTERING K-MEANS
    # ==================================================

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(dff_ml)

    kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
    clusters = kmeans.fit_predict(X_scaled)

    dff_cluster = dff_ml.copy()
    dff_cluster["Cluster"] = clusters.astype(str)

    fig_clusters = px.scatter(
        dff_cluster,
        x="Ingreso_Total",
        y="Ganancia_Neta",
        color="Cluster",
        size="Cantidad",
        title="🔵 Clustering K-Means (k=3)",
        labels={"Cluster": "Segmento"}
    )

    fig_clusters.update_layout(template="plotly_dark")

    # ==================================================
    # CLASIFICACION - PREPARAR TARGET
    # ==================================================

    mediana_ganancia = dff_ml["Ganancia_Neta"].median()
    y = (dff_ml["Ganancia_Neta"] >= mediana_ganancia).astype(int)
    X = dff_ml.drop(columns=["Ganancia_Neta"])

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # ==================================================
    # RANDOM FOREST
    # ==================================================

    rf = RandomForestClassifier(n_estimators=100, random_state=42)
    rf.fit(X_train, y_train)
    acc_rf = rf.score(X_test, y_test)

    cm_rf = confusion_matrix(y_test, rf.predict(X_test))

    fig_rf_confusion = go.Figure(

        data=go.Heatmap(
            z=cm_rf,
            x=["Pred: Baja", "Pred: Alta"],
            y=["Real: Baja", "Real: Alta"],
            colorscale="Blues",
            text=cm_rf,
            texttemplate="%{text}",
            showscale=True
        )

    )

    fig_rf_confusion.update_layout(
        title=f"🌲 Confusion Matrix - Random Forest (Acc: {acc_rf:.2%})",
        template="plotly_dark"
    )

    # ==================================================
    # XGBOOST
    # ==================================================

    xgb = XGBClassifier(
        n_estimators=100,
        random_state=42,
        eval_metric="logloss",
        verbosity=0
    )

    xgb.fit(X_train, y_train)
    acc_xgb = xgb.score(X_test, y_test)

    cm_xgb = confusion_matrix(y_test, xgb.predict(X_test))

    fig_xgb_confusion = go.Figure(

        data=go.Heatmap(
            z=cm_xgb,
            x=["Pred: Baja", "Pred: Alta"],
            y=["Real: Baja", "Real: Alta"],
            colorscale="Greens",
            text=cm_xgb,
            texttemplate="%{text}",
            showscale=True
        )

    )

    fig_xgb_confusion.update_layout(
        title=f"⚡ Confusion Matrix - XGBoost (Acc: {acc_xgb:.2%})",
        template="plotly_dark"
    )

    # ==================================================
    # COMPARACION DE MODELOS
    # ==================================================

    modelos_df = pd.DataFrame({
        "Modelo": ["Random Forest", "XGBoost"],
        "Accuracy": [acc_rf, acc_xgb]
    })

    fig_comparacion = px.bar(
        modelos_df,
        x="Modelo",
        y="Accuracy",
        color="Modelo",
        text="Accuracy",
        title="📊 Comparación de Modelos",
        range_y=[0, 1]
    )

    fig_comparacion.update_traces(
        texttemplate="%{text:.2%}",
        textposition="outside"
    )

    fig_comparacion.update_layout(template="plotly_dark")

    # ==================================================
    # IMPORTANCIA DE VARIABLES (RANDOM FOREST)
    # ==================================================

    importancias_df = pd.DataFrame({
        "Variable": X.columns,
        "Importancia": rf.feature_importances_
    }).sort_values("Importancia", ascending=True)

    fig_importancias = px.bar(
        importancias_df,
        x="Importancia",
        y="Variable",
        orientation="h",
        title="🔍 Importancia de Variables - Random Forest",
        color="Importancia",
        color_continuous_scale="Viridis"
    )

    fig_importancias.update_layout(template="plotly_dark")

    # ==================================================
    # RETURN
    # ==================================================

    return (
        kpis,
        fig_linea,
        fig_categoria,
        fig_tienda,
        fig_box,
        fig_scatter,
        fig_pie,
        fig_heatmap,
        fig_clusters,
        fig_comparacion,
        fig_rf_confusion,
        fig_xgb_confusion,
        fig_importancias
    )


# ======================================================
# EJECUTAR
# ======================================================

if __name__ == "__main__":
    app.run(debug=True, port=8051)